development:
  adapter: mysql2
  encode: utf8
  database: gastos_test
  pool: 5
  timeout: 5000
  username: root
  password: "alfa1625"

production:
  adapter: mysql2
  encode: utf8
  database: gastos
  pool: 5
  timeout: 5000
  username: root
  password: "alfa1625"


